name: "PNPM & Turbo Cache"
description: "PNPM & Turbo Cache"
runs:
  using: "composite"
  steps:
    - name: Cache turbo build setup
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
      name: Install pnpm
      with:
        run_install: false

    - name: Install dependencies
      run: pnpm install
      shell: bash
