name: CI

on:
  workflow_dispatch:
  push:
    branches: ["main"] # remove "react-demo-app" before merge to main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: pr-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: ./.github/workflows/actions/install

      - name: Build
        run: pnpm build


      - name: Test
        run: pnpm test